name: CI/CD Detection Rules Data Loader

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout Main Repository
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: |
          gradle clean build -x test

      - name: Find JAR File
        id: find_jar
        run: |
          echo "Searching for JAR file..."
          echo $GITHUB_WORKSPACE
          JAR_FILE=$(find $GITHUB_WORKSPACE/build/libs -name '*SNAPSHOT.jar')
          echo "JAR_FILE=${JAR_FILE}" >> $GITHUB_ENV

      - name: Deploy to EC2
        if: success()
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "./"
          target: "/home/ubuntu/united-platform/dev/detection-rules"

      - name: Setup new version on Server
        if: success()
        uses: appleboy/ssh-action@master
        env:
          TRUST_STORE_PATH: ${{ secrets.TRUST_STORE_PATH }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}

          script: |
            sudo systemctl restart detection-rules.service
            sudo systemctl restart nginx
